groups:
  - name: "ressources_warnings"
    rules:
      - alert: HighCPUUsageWarning
        expr: (rate(container_cpu_usage_seconds_total{name=~"auth|user|content|social|realtime|bff"}[1m]) * 100) > 70
        for: 5m
        labels:
          severity: warning
          service: "{{$labels.job}}"
        annotations:
          summary: "CPU élevé détecté"
          description: "Le service {{$labels.job}} utilise {{$value}}% de CPU"
      
      - alert: HighMemoryUsageWarning
        expr: (process_resident_memory_bytes{job=~"auth|user|content|social|realtime|bff"} / 1024 / 1024) > 150
        for: 5m
        labels:
          severity: warning
          service: "{{$labels.job}}"
        annotations:
          summary: "Utilisation mémoire élevée"
          description: "Le service {{$labels.job}} utilise {{$value}} MB de RAM"

      