{
 "title": "42Hub",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Usage CPU par service",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=~\"auth|user|content|social|realtime|bff\"}[1m]) * 100",
     "legendFormat": "{{name}} - CPU %"
    }
   ]
  },
  {
   "title": "Mémoire utilisée par service",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\"auth|user|content|social|realtime|bff\"} / 1024 / 1024",
     "legendFormat": "{{name}} - RAM (MB)"
    }
   ]
  },
  {
   "title": "Débit réseau global de l'infrastructure",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".*\"}[1m]))",
     "legendFormat": "Trafic sortant (TX)"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".*\"}[1m]))",
     "legendFormat": "Trafic entrant (RX)"
    }
   ]
  }
 ]
}